global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - backend:5000

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - cadvisor:8080
