FROM node:22-slim AS builder
WORKDIR /app
ENV CI=true
COPY . .
RUN corepack enable && corepack prepare pnpm@9.7.1 --activate
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store pnpm install -r --frozen-lockfile
RUN pnpm prisma:generate && pnpm -w --filter @privacy-advisor/backend build

FROM node:22-slim AS runner
ENV NODE_ENV=production
WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app .
EXPOSE 5000
CMD ["node", "--import", "tsx", "apps/backend/src/index.ts"]
