blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/yourusername/gecko-advisor/security/advisories/new
    about: Please report security vulnerabilities through GitHub Security Advisories
  - name: Discussions
    url: https://github.com/yourusername/gecko-advisor/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/yourusername/gecko-advisor#readme
    about: Read the documentation for usage guides and FAQs
